//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cellphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int ID { get; set; }
        public string HinhAnh { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public int TrangThai { get; set; }
        public System.DateTime Created_at { get; set; }
    }
}
