//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cellphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTGioHang
    {
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public string TrangThai { get; set; }
        public int MaKH { get; set; }
        public double ThanhTien { get; set; }
        public string TenSP { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
