//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cellphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhap
    {
        public int ID { get; set; }
        public int MaPH { get; set; }
        public int MaSP { get; set; }
        public System.DateTime NgayLap { get; set; }
        public double SoLuong { get; set; }
        public double Gia { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
