//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cellphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public int ID { get; set; }
        public int MaKH { get; set; }
        public System.DateTime NgayLap { get; set; }
        public double TongTien { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public string TrangThai { get; set; }
        public Nullable<double> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
