//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cellphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int C_ID { get; set; }
        public string C_Password { get; set; }
        public string C_Email { get; set; }
        public string C_Phone { get; set; }
        public int C_is_Admin { get; set; }
        public Nullable<bool> C_is_Active { get; set; }
        public Nullable<System.DateTime> C_Created_at { get; set; }
        public Nullable<System.DateTime> C_Updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
